# Generated by Django 4.0.4 on 2022-06-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='platos',
            new_name='plato',
        ),
    ]
